name: 📱 Android
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        lib-type:
          - STATIC
          - SHARED
        build-type:
          - Release
          - Debug
    env:
      LIB_TYPE: ${{ matrix.lib-type }}
      CMAKE_BUILD_TYPE: ${{ matrix.build-type }}
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_ID: ${{github.ref}}-${{ matrix.lib-type }}-${{ matrix.build-type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ccache ninja-build gcc-multilib

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew --no-daemon publish
