name: 🐧 Linux
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lib-type:
          - static
          - shared
        build-type:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-${{ matrix.lib-type }}-${{ matrix.build-type }}-${{ github.sha }}
          restore-keys: |
            ${{ github.job }}-${{ matrix.lib-type }}-${{ matrix.build-type }}-

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential ccache libasound2-dev libdbus-1-dev libgl1-mesa-dev libglew-dev libibus-1.0-dev libpulse-dev libreadline6-dev libtbb-dev libudev-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxrender-dev libxss-dev ninja-build pkg-config uuid-dev

      - name: CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=${{ matrix.lib-type }} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build --parallel 2 --target all --config ${{ matrix.build-type }} -- -j2

      - name: Package
        #if: startsWith(github.ref, 'refs/tags/')
        run: cmake --build build --target package --config ${{ matrix.build-type }}

      - name: Upload packages
        #if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: 'U3D-${{ github.job }}-${{ github.sha }}'
          path: build/*.tar.gz
