name: 🖳 Windows
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        lib-type:
          - static
          - shared
        build-type:
          - Release
          - Debug
        architecture:
          - x64
          - Win32
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=${{ matrix.lib-type }} -DURHO3D_PCH=OFF -A ${{ matrix.architecture }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }}

      - name: Package
        #if: startsWith(github.ref, 'refs/tags/')
        run: cmake --build build --target package --config ${{ matrix.build-type }}

      - name: Upload packages
        #if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: 'U3D-${{ github.job }}-${{ github.sha }}'
          path: build/*.zip
